import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { generatePresentationOutline, type SlideOutline } from "@/lib/presentations.functions";
import {
  listTemplates,
  createTemplate,
  renameTemplate,
  deleteTemplate,
  duplicateTemplate,
  setDefaultTemplate,
  getTemplateDownloadUrl,
} from "@/lib/templates.functions";
import { supabase } from "@/integrations/supabase/client";
import { useRef, useState } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Presentation, Sparkles, Download, Trash2, Plus, ArrowUp, ArrowDown, Upload, Copy, Star, Layers } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/presentations")({
  component: PresentationsPage,
});

const THEMES = [
  { id: "professional", name: "Professional", desc: "Clean neutral palette, minimal accents.", colors: ["#0f172a", "#1e293b", "#38bdf8"] },
  { id: "cybersecurity", name: "Cybersecurity", desc: "Dark, neon-cyan, security-ops feel.", colors: ["#020617", "#0891b2", "#22d3ee"] },
  { id: "corporate", name: "Corporate", desc: "Blue + slate, executive style.", colors: ["#0b3d91", "#e2e8f0", "#facc15"] },
  { id: "education", name: "Education", desc: "Warm and approachable.", colors: ["#065f46", "#fde68a", "#f97316"] },
  { id: "business", name: "Business", desc: "Sharp black/white with a red accent.", colors: ["#000000", "#ffffff", "#ef4444"] },
] as const;
type ThemeId = (typeof THEMES)[number]["id"];

function PresentationsPage() {
  const [topic, setTopic] = useState("");
  const [audience, setAudience] = useState("");
  const [slideCount, setSlideCount] = useState(10);
  const [theme, setTheme] = useState<ThemeId>("cybersecurity");
  const [deckTitle, setDeckTitle] = useState("");
  const [slides, setSlides] = useState<SlideOutline[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);

  const gen = useServerFn(generatePresentationOutline);
  const mut = useMutation({
    mutationFn: () => gen({ data: { topic, slideCount, theme, audience: audience || undefined } }),
    onSuccess: (data) => {
      setDeckTitle(data.title);
      setSlides(data.slides);
      toast.success(`${data.slides.length} slides generated`);
    },
    onError: (e: Error) => toast.error(e.message || "Generation failed"),
  });

  async function exportPptx() {
    if (slides.length === 0) return;
    const { default: PptxGenJS } = await import("pptxgenjs");
    const pptx = new PptxGenJS();
    const t = THEMES.find((x) => x.id === theme)!;
    pptx.layout = "LAYOUT_WIDE";
    // Title slide
    const title = pptx.addSlide();
    title.background = { color: t.colors[0].replace("#", "") };
    title.addText(deckTitle || topic, { x: 0.5, y: 2.5, w: 12, h: 1.5, fontSize: 44, bold: true, color: "FFFFFF", fontFace: "Calibri" });
    title.addText("Generated by Kaalu AI", { x: 0.5, y: 4.2, w: 12, h: 0.5, fontSize: 18, color: t.colors[2].replace("#", "") });

    slides.forEach((s, i) => {
      if (i === 0) return; // title covered
      const slide = pptx.addSlide();
      slide.background = { color: "0F172A" };
      slide.addText(s.title, { x: 0.5, y: 0.4, w: 12, h: 1, fontSize: 32, bold: true, color: "FFFFFF" });
      slide.addShape("line", { x: 0.5, y: 1.4, w: 2, h: 0, line: { color: t.colors[2].replace("#", ""), width: 3 } });
      slide.addText(
        s.bullets.map((b) => ({ text: b, options: { bullet: true } })),
        { x: 0.6, y: 1.8, w: 12, h: 5, fontSize: 20, color: "E2E8F0", paraSpaceAfter: 8 },
      );
      if (s.notes) slide.addNotes(s.notes);
      slide.addText(`${i + 1} / ${slides.length}`, { x: 12.2, y: 6.9, w: 1, h: 0.3, fontSize: 10, color: "64748B", align: "right" });
    });

    await pptx.writeFile({ fileName: `${(deckTitle || topic).replace(/[^a-z0-9]+/gi, "_")}.pptx` });
    toast.success("Downloaded .pptx");
  }

  function updateSlide(idx: number, patch: Partial<SlideOutline>) {
    setSlides((prev) => prev.map((s, i) => (i === idx ? { ...s, ...patch } : s)));
  }
  function moveSlide(idx: number, dir: -1 | 1) {
    setSlides((prev) => {
      const next = [...prev];
      const j = idx + dir;
      if (j < 0 || j >= next.length) return prev;
      [next[idx], next[j]] = [next[j], next[idx]];
      return next;
    });
  }
  function deleteSlide(idx: number) {
    setSlides((prev) => prev.filter((_, i) => i !== idx));
  }
  function addSlide() {
    setSlides((prev) => [...prev, { title: "New Slide", bullets: ["Add a point"], notes: "" }]);
  }

  return (
    <div className="p-6 md:p-8 max-w-6xl mx-auto space-y-6">
      <header>
        <div className="text-[10px] uppercase tracking-widest text-muted-foreground">AI Deck Studio</div>
        <h1 className="text-3xl font-semibold neon-text mt-1 flex items-center gap-2">
          <Presentation className="h-6 w-6 text-primary" /> Presentation Generator
        </h1>
        <p className="text-sm text-muted-foreground mt-1">Turn a topic into an editable slide deck powered by Kaalu AI.</p>
      </header>

      <TemplateManager
        selectedTemplateId={selectedTemplateId}
        onSelect={setSelectedTemplateId}
      />

      <section className="glass rounded-xl p-5 border border-white/5 space-y-4">
        <div>
          <label className="text-xs uppercase tracking-widest text-muted-foreground">Topic</label>
          <Textarea
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g. Zero-Trust Architecture for a mid-size fintech"
            className="mt-1 bg-white/5 border-white/10"
            rows={2}
          />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="text-xs uppercase tracking-widest text-muted-foreground">Audience (optional)</label>
            <Input value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="e.g. Executives, engineers, students" className="mt-1 bg-white/5 border-white/10" />
          </div>
          <div>
            <label className="text-xs uppercase tracking-widest text-muted-foreground">
              Slides: <span className="text-primary">{slideCount}</span>
            </label>
            <Slider value={[slideCount]} onValueChange={(v) => setSlideCount(v[0])} min={5} max={20} step={1} className="mt-3" />
          </div>
        </div>

        <div>
          <div className="text-xs uppercase tracking-widest text-muted-foreground mb-2">Theme</div>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-2">
            {THEMES.map((t) => (
              <button
                key={t.id}
                onClick={() => setTheme(t.id)}
                className={`text-left rounded-lg p-3 border transition ${theme === t.id ? "border-primary/60 bg-primary/10" : "border-white/10 hover:border-white/30"}`}
              >
                <div className="flex gap-1 mb-2">
                  {t.colors.map((c) => (<div key={c} className="h-4 w-4 rounded" style={{ background: c }} />))}
                </div>
                <div className="text-sm font-medium">{t.name}</div>
                <div className="text-[11px] text-muted-foreground">{t.desc}</div>
              </button>
            ))}
          </div>
        </div>

        <div className="flex gap-2">
          <Button onClick={() => mut.mutate()} disabled={!topic.trim() || mut.isPending}>
            <Sparkles className="h-4 w-4 mr-1" /> {mut.isPending ? "Generating…" : "Generate Outline"}
          </Button>
          <Button variant="secondary" onClick={exportPptx} disabled={slides.length === 0}>
            <Download className="h-4 w-4 mr-1" /> Export .pptx
          </Button>
        </div>
      </section>

      {slides.length > 0 && (
        <section>
          <div className="flex items-center gap-3 mb-3">
            <Input value={deckTitle} onChange={(e) => setDeckTitle(e.target.value)} className="max-w-md bg-white/5 border-white/10 text-lg font-semibold" />
            <Button size="sm" variant="ghost" onClick={addSlide}><Plus className="h-4 w-4 mr-1" /> Add slide</Button>
          </div>
          <div className="space-y-3">
            {slides.map((s, i) => (
              <div key={i} className="glass rounded-xl p-4 border border-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-[10px] uppercase tracking-widest text-muted-foreground">Slide {i + 1}</span>
                  <div className="ml-auto flex gap-1">
                    <Button size="icon" variant="ghost" onClick={() => moveSlide(i, -1)}><ArrowUp className="h-3.5 w-3.5" /></Button>
                    <Button size="icon" variant="ghost" onClick={() => moveSlide(i, 1)}><ArrowDown className="h-3.5 w-3.5" /></Button>
                    <Button size="icon" variant="ghost" onClick={() => deleteSlide(i)}><Trash2 className="h-3.5 w-3.5" /></Button>
                  </div>
                </div>
                <Input
                  value={s.title}
                  onChange={(e) => updateSlide(i, { title: e.target.value })}
                  className="bg-white/5 border-white/10 font-semibold mb-2"
                />
                <Textarea
                  value={s.bullets.join("\n")}
                  onChange={(e) => updateSlide(i, { bullets: e.target.value.split("\n").filter(Boolean) })}
                  className="bg-white/5 border-white/10 text-sm"
                  rows={Math.max(3, s.bullets.length)}
                />
                <Input
                  value={s.notes ?? ""}
                  onChange={(e) => updateSlide(i, { notes: e.target.value })}
                  placeholder="Speaker notes (optional)"
                  className="mt-2 bg-white/5 border-white/10 text-xs"
                />
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}

function TemplateManager({
  selectedTemplateId,
  onSelect,
}: {
  selectedTemplateId: string | null;
  onSelect: (id: string | null) => void;
}) {
  const qc = useQueryClient();
  const listFn = useServerFn(listTemplates);
  const createFn = useServerFn(createTemplate);
  const renameFn = useServerFn(renameTemplate);
  const deleteFn = useServerFn(deleteTemplate);
  const duplicateFn = useServerFn(duplicateTemplate);
  const setDefaultFn = useServerFn(setDefaultTemplate);
  const downloadFn = useServerFn(getTemplateDownloadUrl);
  const fileRef = useRef<HTMLInputElement>(null);
  const [uploading, setUploading] = useState(false);

  const { data: templates = [] } = useQuery({
    queryKey: ["pptx-templates"],
    queryFn: () => listFn(),
  });

  async function handleUpload(file: File) {
    if (!file.name.toLowerCase().endsWith(".pptx")) {
      toast.error("Only .pptx files are supported");
      return;
    }
    if (file.size > 25 * 1024 * 1024) {
      toast.error("Template must be under 25 MB");
      return;
    }
    setUploading(true);
    try {
      const { data: userData } = await supabase.auth.getUser();
      if (!userData.user) throw new Error("Sign in required");
      const path = `${userData.user.id}/${crypto.randomUUID()}.pptx`;
      const { error } = await supabase.storage
        .from("pptx-templates")
        .upload(path, file, {
          contentType:
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        });
      if (error) throw error;
      await createFn({
        data: {
          name: file.name.replace(/\.pptx$/i, ""),
          storage_path: path,
          size_bytes: file.size,
        },
      });
      toast.success("Template uploaded");
      qc.invalidateQueries({ queryKey: ["pptx-templates"] });
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Upload failed";
      toast.error(msg);
    } finally {
      setUploading(false);
      if (fileRef.current) fileRef.current.value = "";
    }
  }

  async function preview(id: string) {
    try {
      const { url, name } = await downloadFn({ data: { id } });
      const a = document.createElement("a");
      a.href = url;
      a.target = "_blank";
      a.rel = "noreferrer";
      a.download = `${name}.pptx`;
      a.click();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Download failed");
    }
  }

  return (
    <section className="glass rounded-xl p-5 border border-white/5">
      <div className="flex items-center justify-between mb-3">
        <div>
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">Template Manager</div>
          <h2 className="text-lg font-semibold flex items-center gap-2 mt-0.5">
            <Layers className="h-4 w-4 text-primary" /> Presentation templates
          </h2>
          <p className="text-xs text-muted-foreground mt-1">
            Upload a .pptx to reuse its theme, fonts, and layouts. The AI outline slots into your chosen template.
          </p>
        </div>
        <div>
          <input
            ref={fileRef}
            type="file"
            accept=".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation"
            className="hidden"
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) handleUpload(f);
            }}
          />
          <Button size="sm" variant="secondary" onClick={() => fileRef.current?.click()} disabled={uploading}>
            <Upload className="h-4 w-4 mr-1" /> {uploading ? "Uploading…" : "Upload .pptx"}
          </Button>
        </div>
      </div>

      {templates.length === 0 ? (
        <div className="text-xs text-muted-foreground py-2">
          No templates yet. Upload one to keep your decks on-brand.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
          <button
            onClick={() => onSelect(null)}
            className={`text-left rounded-lg p-3 border transition ${
              selectedTemplateId === null ? "border-primary/60 bg-primary/10" : "border-white/10 hover:border-white/30"
            }`}
          >
            <div className="text-sm font-medium">Kaalu default</div>
            <div className="text-[11px] text-muted-foreground">Built-in themed generator</div>
          </button>
          {templates.map((t) => (
            <TemplateCard
              key={t.id}
              template={t}
              selected={selectedTemplateId === t.id}
              onSelect={() => onSelect(t.id)}
              onRename={async (name) => {
                await renameFn({ data: { id: t.id, name } });
                qc.invalidateQueries({ queryKey: ["pptx-templates"] });
              }}
              onDelete={async () => {
                if (!window.confirm(`Delete "${t.name}"?`)) return;
                await deleteFn({ data: { id: t.id } });
                if (selectedTemplateId === t.id) onSelect(null);
                toast.success("Template deleted");
                qc.invalidateQueries({ queryKey: ["pptx-templates"] });
              }}
              onDuplicate={async () => {
                await duplicateFn({ data: { id: t.id } });
                toast.success("Template duplicated");
                qc.invalidateQueries({ queryKey: ["pptx-templates"] });
              }}
              onSetDefault={async () => {
                await setDefaultFn({ data: { id: t.id } });
                toast.success("Set as default");
                qc.invalidateQueries({ queryKey: ["pptx-templates"] });
              }}
              onPreview={() => preview(t.id)}
            />
          ))}
        </div>
      )}
    </section>
  );
}

function TemplateCard({
  template,
  selected,
  onSelect,
  onRename,
  onDelete,
  onDuplicate,
  onSetDefault,
  onPreview,
}: {
  template: {
    id: string;
    name: string;
    is_default: boolean;
    size_bytes: number;
    created_at: string;
  };
  selected: boolean;
  onSelect: () => void;
  onRename: (name: string) => Promise<void>;
  onDelete: () => void;
  onDuplicate: () => void;
  onSetDefault: () => void;
  onPreview: () => void;
}) {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(template.name);
  return (
    <div
      className={`rounded-lg p-3 border transition ${
        selected ? "border-primary/60 bg-primary/10" : "border-white/10 hover:border-white/30"
      }`}
    >
      <button onClick={onSelect} className="text-left w-full">
        <div className="flex items-center gap-2">
          {editing ? (
            <Input
              autoFocus
              value={name}
              onChange={(e) => setName(e.target.value)}
              onClick={(e) => e.stopPropagation()}
              onBlur={async () => {
                setEditing(false);
                if (name.trim() && name !== template.name) await onRename(name.trim());
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
                if (e.key === "Escape") {
                  setName(template.name);
                  setEditing(false);
                }
              }}
              className="h-6 text-sm"
            />
          ) : (
            <div className="text-sm font-medium truncate flex items-center gap-1">
              {template.is_default && <Star className="h-3.5 w-3.5 text-primary fill-primary" />}
              {template.name}
            </div>
          )}
        </div>
        <div className="text-[11px] text-muted-foreground">
          {(template.size_bytes / 1024).toFixed(0)} KB · {new Date(template.created_at).toLocaleDateString()}
        </div>
      </button>
      <div className="mt-2 flex flex-wrap gap-1">
        <Button size="sm" variant="ghost" className="h-6 px-2 text-[11px]" onClick={onPreview}>
          <Download className="h-3 w-3 mr-1" /> Preview
        </Button>
        <Button size="sm" variant="ghost" className="h-6 px-2 text-[11px]" onClick={() => setEditing(true)}>
          Rename
        </Button>
        <Button size="sm" variant="ghost" className="h-6 px-2 text-[11px]" onClick={onDuplicate}>
          <Copy className="h-3 w-3 mr-1" /> Duplicate
        </Button>
        {!template.is_default && (
          <Button size="sm" variant="ghost" className="h-6 px-2 text-[11px]" onClick={onSetDefault}>
            <Star className="h-3 w-3 mr-1" /> Default
          </Button>
        )}
        <Button size="sm" variant="ghost" className="h-6 px-2 text-[11px] text-destructive" onClick={onDelete}>
          <Trash2 className="h-3 w-3" />
        </Button>
      </div>
    </div>
  );
}