/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ArchiveSourceRouteImport } from './routes/archive.$source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSourceRoute = ArchiveSourceRouteImport.update({
  id: '/archive/$source',
  path: '/archive/$source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive/$source': typeof ArchiveSourceRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive/$source': typeof ArchiveSourceRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive/$source': typeof ArchiveSourceRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archive/$source' | '/article/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archive/$source' | '/article/$id'
  id: '__root__' | '/' | '/archive/$source' | '/article/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveSourceRoute: typeof ArchiveSourceRoute
  ArticleIdRoute: typeof ArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$source': {
      id: '/archive/$source'
      path: '/archive/$source'
      fullPath: '/archive/$source'
      preLoaderRoute: typeof ArchiveSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveSourceRoute: ArchiveSourceRoute,
  ArticleIdRoute: ArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
